[project]
name = "web3cli"
version = "0.1.1"
description = "Interact with blockchains and smart contracts using the command line"
authors = [
    {name = "coccoinomane", email = "coccoinomane@gmail.com"},
]
readme = "README.md"
keywords = ["web3", "cli", "blockchain", "ethereum", "evm"]
license = {text = "MIT"}
requires-python = ">=3.10,<4"
dependencies = [
    "cement[jinja2]>=3.0.8",
    "web3client>=0.3.4",
]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.3",
    "mypy>=0.982",
]

[tool.pdm.scripts]
test = "python -m pytest tests"
publish_test = "pdm publish -r ${PDM_PUBLISH_TEST_REPO} -u ${PDM_PUBLISH_TEST_USERNAME} -P ${PDM_PUBLISH_TEST_PASSWORD}"
clean = "find . -name '*.py[co]' -delete"
docker = "pdm run clean && docker build -t web3cli:latest ."

[project.urls]
homepage = "https://github.com/coccoinomane/web3cli"
repository = "https://github.com/coccoinomane/web3cli"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.build]
includes = ["src"]

[tool.black]
line-length = 88

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
strict_optional = false
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_any_unimported = false
disallow_untyped_calls = true
exclude = [
    '__pypackages__',
]