### Web3 Cli Configuration Settings
###
### All settings can be overriden using snake case environment
### variables, for example 'export WEB3CLI_DEFAULT_NETWORK=ethereum'
###
### Copy this file to ~/.web3cli/conf/web3cli.yml if you need
### to change a settings in a more permanent way.
###
### Please be aware that any value specified by means of an environment
### variable take precedence on the file's content.
---

web3cli:
  ### Toggle application level debug
  debug: false
  ### Use this network unless otherwise specified
  default_network: "ethereum"
  ### Location of the database - will be created if it does not exist.
  db_file: "~/.web3cli/database/web3cli.sqlite"

web3cli_test:
  ### Database to be used for tests - it will be deleted before
  ### each test run
  db_file: "~/.web3cli/database/web3cli_test.sqlite"

log.colorlog:
  ### Where the log file lives (no log file by default)
  file: null
  ### The level for which to log.  One of: info, warning, error, fatal, debug
  level: info
  ### Whether or not to log to console
  to_console: true
  ### Whether or not to rotate the log file when it reaches `max_bytes`
  rotate: false
  ### Max size in bytes that a log file can grow until it is rotated.
  max_bytes: 512000
  ### The maximum number of log files to maintain when rotating
  max_files: 4
